server:
    port: 8088
    tomcat:
        max-swallow-size: 2MB

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/my_net?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    thymeleaf:
        cache: false
        encoding: utf-8
        servlet:
            content-type: text/html
        mode: HTML

    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 2MB

mybatis-plus:
    mapper-locations: classpath:mybatis/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
